name: signal
description: A starting point for Dart libraries or applications.
version: 1.1.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  logging: ^1.2.0
  message_pack_dart: ^2.0.1
  sse_channel3: ^0.0.5
  tuple: ^2.0.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  collection: ^1.15.0
  flutter_test:
    sdk: flutter
  quiver: ^3.2.1
  rxdart: ^0.27.7
  test: ^1.16.2
